apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: aws-kbs-test
  name: aws-kbs-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-kbs-test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aws-kbs-test
    spec:
      containers:
      - image: abdeldayem/aws-kbs-test:0.0.1.Release
        imagePullPolicy: Always
        name: aws-kbs-test
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: aws-kbs-test
  name: aws-kbs-test
  namespace: default
spec:
  ports:
  - nodePort: 30941
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: aws-kbs-test
  sessionAffinity: None
  type: LoadBalancer
